### ISSUE TITLE
how to test-it locally on devnet.

### ISSUE THREAD

**Issue by livcoding2** [cryptoloutre/solana-tools#9]
Soory about my ingnorance, but how to test-it locally on devnet?

**Comment by cryptoloutre** [comment]
Hi,

1- clone the repo: `https://github.com/cryptoloutre/solana-tools.git`
2- install the dependencies: `npm install`
3- open the `src/pages/_app.tsx` file
4- change the endpoint with a devnet one. You can use `https://api.devnet.solana.com` or since there are rate limits you can get one on [Helius](https://dev.helius.xyz/rpcs/my)
5- save the file and run: `npm run dev`
